/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ACheckbox: typeof import('ant-design-vue/es')['Checkbox']
    ACheckboxGroup: typeof import('ant-design-vue/es')['CheckboxGroup']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    Animate: typeof import('./src/components/ThreeD/Animate.vue')['default']
    ATimeline: typeof import('ant-design-vue/es')['Timeline']
    ATimelineItem: typeof import('ant-design-vue/es')['TimelineItem']
    Draw: typeof import('./src/components/ThreeD/Draw.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    Measure: typeof import('./src/components/ThreeD/Measure.vue')['default']
    reactive: typeof import('./src/components/06_ref reactive.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThreeD: typeof import('./src/components/views/ThreeD.vue')['default']
    ThreeForm: typeof import('./src/components/ThreeD/ThreeForm.vue')['default']
    ThreeFrom: typeof import('./src/components/ThreeD/ThreeFrom.vue')['default']
    toRefs: typeof import('./src/components/07_toRef toRefs.vue')['default']
    TwoD: typeof import('./src/components/views/TwoD.vue')['default']
    Visual: typeof import('./src/components/ThreeD/Visual.vue')['default']
    Weather: typeof import('./src/components/ThreeD/Weather.vue')['default']
  }
}
